#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptumPresence.Data.Hoteling
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Hoteling")]
	public partial class HotelingDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public HotelingDataContext() : 
				base(global::OptumPresence.Data.Properties.Settings.Default.HotelingConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HotelingDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HotelingDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HotelingDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HotelingDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _UserUID;
		
		private string _Username;
		
		private string _Password;
		
		private string _FirstName;
		
		private string _LastName;
		
		private System.Nullable<long> _PositionUID;
		
		private System.Nullable<long> _TeamUID;
		
		private System.DateTime _RecordCreateDate;
		
		private string _RecordCreateUserID;
		
		private System.DateTime _RecordUpdateDate;
		
		private string _RecordUpdateUserID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserUIDChanging(long value);
    partial void OnUserUIDChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnPositionUIDChanging(System.Nullable<long> value);
    partial void OnPositionUIDChanged();
    partial void OnTeamUIDChanging(System.Nullable<long> value);
    partial void OnTeamUIDChanged();
    partial void OnRecordCreateDateChanging(System.DateTime value);
    partial void OnRecordCreateDateChanged();
    partial void OnRecordCreateUserIDChanging(string value);
    partial void OnRecordCreateUserIDChanged();
    partial void OnRecordUpdateDateChanging(System.DateTime value);
    partial void OnRecordUpdateDateChanged();
    partial void OnRecordUpdateUserIDChanging(string value);
    partial void OnRecordUpdateUserIDChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserUID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long UserUID
		{
			get
			{
				return this._UserUID;
			}
			set
			{
				if ((this._UserUID != value))
				{
					this.OnUserUIDChanging(value);
					this.SendPropertyChanging();
					this._UserUID = value;
					this.SendPropertyChanged("UserUID");
					this.OnUserUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionUID", DbType="BigInt")]
		public System.Nullable<long> PositionUID
		{
			get
			{
				return this._PositionUID;
			}
			set
			{
				if ((this._PositionUID != value))
				{
					this.OnPositionUIDChanging(value);
					this.SendPropertyChanging();
					this._PositionUID = value;
					this.SendPropertyChanged("PositionUID");
					this.OnPositionUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamUID", DbType="BigInt")]
		public System.Nullable<long> TeamUID
		{
			get
			{
				return this._TeamUID;
			}
			set
			{
				if ((this._TeamUID != value))
				{
					this.OnTeamUIDChanging(value);
					this.SendPropertyChanging();
					this._TeamUID = value;
					this.SendPropertyChanged("TeamUID");
					this.OnTeamUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordCreateDate", DbType="Date NOT NULL")]
		public System.DateTime RecordCreateDate
		{
			get
			{
				return this._RecordCreateDate;
			}
			set
			{
				if ((this._RecordCreateDate != value))
				{
					this.OnRecordCreateDateChanging(value);
					this.SendPropertyChanging();
					this._RecordCreateDate = value;
					this.SendPropertyChanged("RecordCreateDate");
					this.OnRecordCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordCreateUserID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RecordCreateUserID
		{
			get
			{
				return this._RecordCreateUserID;
			}
			set
			{
				if ((this._RecordCreateUserID != value))
				{
					this.OnRecordCreateUserIDChanging(value);
					this.SendPropertyChanging();
					this._RecordCreateUserID = value;
					this.SendPropertyChanged("RecordCreateUserID");
					this.OnRecordCreateUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordUpdateDate", DbType="Date NOT NULL")]
		public System.DateTime RecordUpdateDate
		{
			get
			{
				return this._RecordUpdateDate;
			}
			set
			{
				if ((this._RecordUpdateDate != value))
				{
					this.OnRecordUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._RecordUpdateDate = value;
					this.SendPropertyChanged("RecordUpdateDate");
					this.OnRecordUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordUpdateUserID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RecordUpdateUserID
		{
			get
			{
				return this._RecordUpdateUserID;
			}
			set
			{
				if ((this._RecordUpdateUserID != value))
				{
					this.OnRecordUpdateUserIDChanging(value);
					this.SendPropertyChanging();
					this._RecordUpdateUserID = value;
					this.SendPropertyChanged("RecordUpdateUserID");
					this.OnRecordUpdateUserIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
